### ISSUE TITLE
404 while searching

### ISSUE THREAD

**Issue by niladam** [dillingham/nova-attach-many#8]
Hello,

I'm using the latest nova on a valet install with MariaDB, and i'm getting a 404 while searching for anything in the nova (the main search) dashboard.

The error is 404, and it appears to relate to `dillingham/nova-attach-many/src/AttachMany.php` - line 75.

I'm not using any policies (for now) and therefore it appears that this is what's causing a 404.

Am i required to use policies with this ?

**Comment by niladam** [comment]
So, if i update the `authorize` to simply `return true` my search works.

I don't have any policies registered that could affect this.

For now, i'm using this:

```php
    public function authorize(Request $request)
    {
        return true;
        // return call_user_func([ $this->resourceClass, 'authorizedToViewAny'], $request)
        // && $request->newResource()->authorizedToAttachAny($request, $this->resourceClass::newModel())
        // && parent::authorize($request);
    }
```

**Comment by dillingham** [comment]
@niladam thanks for catching that. Is fixed in 1.0.5

**Comment by niladam** [comment]
@dillingham - Thank you for your work buddy! I really appreciate it!:)

**Comment by ahmedkandel** [comment]
@niladam is the fix working for you if you use policies as i got the same issue but the resource has policy.
@dillingham could the fix on #20 be merged or it do you think of another solution? Thanks.

**Comment by rikless** [comment]
It looks like it's not fixed. Have the same issue there.
Trying this PR https://github.com/dillingham/nova-attach-many/pull/20 make all working good
